### ISSUE TITLE
Write up GUI package README

### ISSUE THREAD

**Issue by froi** [github/github-artifact-exporter#1]
Our GUI package is lacking a comprehensive README file.

## TODOs

- [ ] Add screen shots section
- [ ] Add `contribute` or `developers` sections with build instructions
- [ ] _Optional_ Add a Gif showing off the usage of the application
